name: Go
on: [push, pull_request]
jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version:
          - '1.12.x'
          - '1.13.x'
          - '1.14.x'
          - '1.15.x'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -race -coverprofile="coverage.out" ./

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        fail_ci_if_error: true
